### ISSUE TITLE
Please check images and send me Sub title - BTN Academy

### ISSUE THREAD

**Issue by satyajitbtn** [Malvika-BTN/India-Team#16]
Hi malvika,

**Images added in this article** please check and send me sub title for the same,
https://docs.google.com/document/d/161LpRMoCY8O4a4A5yNUy54RLMDw_t8w-cxULf_Dk0NU/edit

this will schedule for the 17.02.2017

please do needful,

**Comment by Malvika-BTN** [comment]
sent as comment.
