### ISSUE TITLE
Photoshop on computers

### ISSUE THREAD

**Issue by Malvika-BTN** [Malvika-BTN/India-Team#18]
Please install on all PCs.

**Comment by satyajitbtn** [comment]
Installed on all the PC except Nick.

**Comment by Malvika-BTN** [comment]
Install, then close the ticket.




-------- Original message --------From: satyajitbtn <notifications@github.com> Date: 22/02/2017  6:16 PM  (GMT+05:30) To: Malvika-BTN/India-Team <India-Team@noreply.github.com> Cc: Malvika-BTN <malvika@beveragetradenetwork.com>, Author <author@noreply.github.com> Subject: Re: [Malvika-BTN/India-Team] Photoshop on computers (#18) 
Installed on all the PC except Nick.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Malvika-BTN/India-Team","title":"Malvika-BTN/India-Team","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Malvika-BTN/India-Team"}},"updates":{"snippets":[{"icon":"PERSON","message":"@satyajitbtn in #18: Installed on all the PC except Nick. "}],"action":{"name":"View Issue","url":"https://github.com/Malvika-BTN/India-Team/issues/18#issuecomment-281659506"}}}
