### ISSUE TITLE
github accounts

### ISSUE THREAD

**Issue by Malvika-BTN** [Malvika-BTN/India-Team#25]
everyone create github accounts and get assigned to this directory.

**Comment by Malvika-BTN** [comment]
@satyajitbtn please mention these accounts here and i can add them to the directory

**Comment by satyajitbtn** [comment]
@Malvika-BTN Here is github account details.

1. Jen
User Name: Jenbtn
Email: jen@beveragetradenetwork.com
2. Brinda
User Name: brindabtn
Email: brinda@beveragetradenetwork.com
3. Juhi
User Name: juhiBTN
Email: juhi@beveragetradenetwork.com
4. Chinka
User Name: chinkabtn
Email: chinka@beveragetradenetwork.com
5. Yagnesh
User Name: yagneshbtn
Email: yagnesh@beveragetradenetwork.com
6. amy
User Name: AmiSmith
Email: amy@beveragetradenetwork.com
