### ISSUE TITLE
IBWSS SFO website view error

### ISSUE THREAD

**Issue by justinbarnesbtn** [Malvika-BTN/India-Team#60]
IBWSS SFO errors in website view that needs to be corrected

![set up your meetings_space visitor zone log in](https://user-images.githubusercontent.com/30334876/28516517-20f2d6f6-707f-11e7-90e4-495b4da68c63.jpg)
![nick s email correction removal of full stop](https://user-images.githubusercontent.com/30334876/28516526-2b878918-707f-11e7-8e6f-81b47920be93.jpg)

**Comment by satyajitbtn** [comment]
Done.
